### PR TITLE
docs: docker faq

### PR DESCRIPTION
**Pull request by cpvalente**
Adding some clarification about the WebSocket setup

@alex-Arc, do you think this is sufficient?
Lets also update the docker compose now

### CODE REVIEW

**Comment by alex-Arc** [comment]
Maybe the default compose should not contain the preloaded-db volume 
I think it leads to more confusion than good

and maybe we should set the default TZ to something other than Asia?
or maybe that is to force people to fix it and not just get lucky?

```
version: "3"

services:
  ontime:
    container_name: ontime
    image: getontime/ontime:latest
    ports:
      - "4001:4001/tcp"
      - "8888:8888/udp"
      - "9999:9999/udp"
    volumes:
      - "./ontime-db:/external/projects/"
      - "./ontime-styles:/external/styles/"
      - "./ontime-external:/external/external/"
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped
```

**Comment by cpvalente** [comment]
> Maybe the default compose should not contain the preloaded-db volume

I am not sure, is this not important for users? We need an interface to the db. I would classify this as fundamental for a usable docker instance. Maybe I misunderstood?

> and maybe we should set the default TZ to something other than Asia?
or maybe that is to force people to fix it and not just get lucky?

Yes, that is the idea.
Most users are not in that timezone, so they will need to find a way to fix it, hopefully this is obvious enough.
We could include timezone for our largest user base (CET) as an alternative. What do you think?

**Comment by cpvalente** [comment]
Hi @lukestein, I notice you have been using the docker image.
Can you give us some feedback on this changes?

**Comment by lukestein** [comment]
All in all, this looks great.

My few small suggestions to consider are

- [ ] Consider at line 54 saying something like
> Ontime serves its web pages on port 4001. `4001:4001/tcp` binds local port 4001 to the same container port. You could instead use something like `80:4001/tcp` to instead reach Ontime using local port 80 (the default for http) and URLs like `http://host` instead of `http://host:4001`.

- [ ] Maybe explain something like
> By default, Ontime stores its files in three directories: `/external/projects/`, `/external/styles/`, and `/external/external/`. These three paths can be bound to individual host directories as in the sample docker-compose file, or you can bind a single host directory to `/external` for Ontime to store all its files in.

**Comment by cpvalente** [comment]
Nice, great tips @lukestein

How about now?

I might be overplaying my hand here with the mention of the external directory, we dont currently have documentation for it and few users know of the feature

**Comment by lukestein** [comment]
It's great!!

**Review by lukestein — APPROVED** [review]

**Comment by cpvalente** [comment]
Thank you @lukestein , would you be against me making you a collaborator here (or in Ontime), that would make it easier for you to make changes and comments

**Comment by lukestein** [comment]
Honored and excited (as long as your expectations of me stay modest 🤜🤛)

**Pull request merged**
