### PR TITLE
docs: whats new in v3

### PR DESCRIPTION
**Pull request by cpvalente**
small update on the main changes we see in v3

### CODE REVIEW

**Review by alex-Arc — APPROVED** [review]
;-)

**Comment by cpvalente** [comment]
@alex-Arc do you think there is anything important missing?

**Comment by alex-Arc** [comment]
hmmm not sure
maybe somthing like  "Improved workflow in editor" <-- the new buttons and shortcuts

**Comment by cpvalente** [comment]
> hmmm not sure maybe somthing like "Improved workflow in editor" <-- the new buttons and shortcuts

good point

when we land on the shortcuts I will make a quick tip about it
I am also not sure the we should recover the button as per our conversation the other day

lets see...

**Pull request merged**
