### PR TITLE
sheet guide

### PR DESCRIPTION
**Pull request by alex-Arc**
the file should be moved some where else and needs better text

### CODE REVIEW

**Comment by cpvalente** [comment]
> the file should be moved some where else and needs better text

Thank you! I can work with the text and layout. Any chance you could provide screenshots for the apontei-me side?

**Comment by alex-Arc** [comment]
> apontei-me

unsure what this is?

**Comment by cpvalente** [comment]
> > apontei-me
> 
> 
> 
> unsure what this is?

Haha, it was supposed to day app side which you have done

**Comment by cpvalente** [comment]
@lukestein, could we have your help with sanity checking here and giving some feedback on phrasing?

I am under the impression that users find the feature complex. For now, documentation is the best we can do to make it more accessible

**Comment by cpvalente** [comment]
Hi @lukestein , quick follow up here.

We have somehow forgotten this, do you think you could take a look at the suggestions?

We get many questions about google-sheets I think we should merge something quickly, at this point, not great is better than nothing

**Comment by alex-Arc** [comment]
@cpvalente Very Nice! :)

**Review by cpvalente — APPROVED** [review]
Good work

**Pull request merged**
